# Generated by Django 2.2.12 on 2020-08-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddedbyindividualdoctor',
            name='practicing_since',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='useraddedbyindividualdoctor',
            name='reg_no_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='useraddedbyindividualdoctor',
            name='reg_no_state',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='useraddedbyindividualdoctor',
            name='speciality1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='useraddedbyindividualdoctor',
            name='speciality2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='useraddedbyindividualdoctor',
            name='speciality3',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
