# Generated by Django 3.0 on 2020-08-30 15:20

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='register_link',
            field=jsonfield.fields.JSONField(),
        ),
    ]
