# Generated by Django 3.0 on 2020-08-31 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200830_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que', models.CharField(blank=True, max_length=255, null=True)),
                ('webregister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Webregister')),
            ],
        ),
    ]
