# Generated by Django 3.0 on 2020-09-01 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200901_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='register_link',
            new_name='reg_link',
        ),
    ]
