# Generated by Django 3.0 on 2020-09-01 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200901_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='reg_link',
            new_name='register_link',
        ),
    ]
