# Generated by Django 3.0 on 2020-09-02 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200901_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rlink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_link', jsonfield.fields.JSONField(blank=True)),
                ('customUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('webregister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Webregister')),
            ],
        ),
    ]
