# Generated by Django 3.0 on 2020-09-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rlink',
            name='register_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
