# Generated by Django 3.0 on 2020-09-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200902_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='webregister',
            name='password',
            field=models.CharField(default='somepassword', max_length=255),
            preserve_default=False,
        ),
    ]
