# Generated by Django 3.0 on 2020-09-06 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200906_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='register_link',
        ),
    ]
