# Generated by Django 3.0 on 2020-09-06 10:03

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200906_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='register_link',
            field=jsonfield.fields.JSONField(blank=True, default=[], null=True),
        ),
    ]
