# Generated by Django 3.0 on 2020-09-07 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_customuser_register_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField()),
                ('last_logout', models.DateTimeField()),
                ('loginuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('webregister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Webregister')),
            ],
        ),
    ]
